# Generated by Django 2.0.5 on 2018-12-17 11:15

import delire.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('brouillon', models.BooleanField(default=True)),
                ('fichier', models.FileField(max_length=200, upload_to=delire.models.PathAndRename('documents/'))),
                ('typeDoc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ecrit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delire.Document')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Noeud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'AP-HP'), (1, 'Hopital'), (2, 'Pole'), (3, 'Service'), (4, 'Unite-Hospitaliere'), (5, 'Unite-Soin')], default=2)),
                ('pere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delire.Noeud')),
            ],
        ),
        migrations.CreateModel(
            name='NoeudSpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noeud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delire.Noeud')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=500)),
                ('telephone', models.CharField(max_length=14)),
                ('situationFamiliale', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delire.Personne')),
                ('job', models.IntegerField(choices=[(0, 'Médecin'), (1, 'Secrétaire'), (2, 'DataManager'), (3, 'Aide-Soignant')], default=0)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('delire.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delire.Personne')),
                ('numSS', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('delire.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='personne',
            name='linkedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delire.Noeud'),
        ),
        migrations.AddField(
            model_name='noeudspe',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delire.Patient'),
        ),
        migrations.AddField(
            model_name='noeud',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delire.Employe'),
        ),
        migrations.AddField(
            model_name='empspe',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delire.Employe'),
        ),
        migrations.AddField(
            model_name='empspe',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delire.Patient'),
        ),
        migrations.AddField(
            model_name='ecrit',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delire.Employe'),
        ),
        migrations.AddField(
            model_name='document',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delire.Patient'),
        ),
    ]
