# Generated by Django 2.1.4 on 2019-01-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='mail',
            new_name='email',
        ),
    ]
