# Generated by Django 2.1.4 on 2019-02-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noeud',
            name='pere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delire.Noeud'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='lieuNaissance',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='situationFamiliale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='telephone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
