# Generated by Django 2.0.3 on 2019-03-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='sexe',
            field=models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], default='F', max_length=1),
        ),
    ]
