# Generated by Django 2.0.3 on 2019-04-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='numSS',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
